# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Learner.get_preds": "00_inference.ipynb",
         "Learner.predict": "00_inference.ipynb",
         "TabularLearner.predict": "00_inference.ipynb",
         "base_error": "01_tabular_interpretation.ipynb",
         "PermutationImportance": "01_tabular_interpretation.ipynb",
         "ShapInterpretation": "01_tabular_shap_interp.ipynb"}

modules = ["inference.py",
           "tabular/interpretation.py",
           "tabular/shap/core.py",
           "tabular/shap/interp.py"]

doc_url = "https://muellerzr.github.io/fastinference/"

git_url = "https://github.com/muellerzr/fastinference/tree/master/"

def custom_doc_links(name): return None
