# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Learner.get_preds": "00_inference.ipynb",
         "Learner.predict": "00_inference.ipynb",
         "TabularLearner.predict": "00_inference.ipynb",
         "soft_import": "00_soft_dependencies.ipynb",
         "soft_imports": "00_soft_dependencies.ipynb",
         "SoftDependencies": "00_soft_dependencies.ipynb",
         "LMLearner.get_preds": "00a_inference.text.ipynb",
         "TextLearner.get_preds": "00a_inference.text.ipynb",
         "LMLearner.predict": "00a_inference.text.ipynb",
         "TextLearner.intrinsic_attention": "00a_inference.text.ipynb",
         "get_information": "00b_inference.export.ipynb",
         "Learner.to_fastinference": "00b_inference.export.ipynb",
         "Interpret": "01_tabular.core.ipynb",
         "sv_var": "01_tabular.core.ipynb",
         "ld_var": "01_tabular.core.ipynb",
         "list_diff": "01_tabular.core.ipynb",
         "which_elms": "01_tabular.core.ipynb",
         "is_in_list": "01_tabular.core.ipynb",
         "listify": "01_tabular.core.ipynb",
         "isNone": "01_tabular.core.ipynb",
         "isNotNone": "01_tabular.core.ipynb",
         "base_error": "01_tabular.interpretation.ipynb",
         "TabularLearner.feature_importance": "01_tabular.interpretation.ipynb",
         "TabularLearner.get_top_corr_dict": "01_tabular.interpretation.ipynb",
         "TabularLearner.plot_dendrogram": "01_tabular.interpretation.ipynb",
         "PartDep": "01_tabular.pd.ipynb",
         "InterpretWaterfall": "01_tabular.waterfall.ipynb",
         "TabDataLoader.get_losses": "02_class_confusion.ipynb",
         "TfmdDL.get_losses": "02_class_confusion.ipynb",
         "ClassConfusion": "02_class_confusion.ipynb",
         "ShapInterpretation": "02_shap.interp.ipynb",
         "fastONNX": "03_onnx.ipynb"}

modules = ["inference/inference.py",
           "soft_dependencies.py",
           "inference/text.py",
           "inference/export.py",
           "tabular/core.py",
           "tabular/interpretation.py",
           "tabular/pd.py",
           "tabular/waterfall.py",
           "class_confusion.py",
           "tabular/shap/core.py",
           "tabular/shap/interp.py",
           "onnx.py"]

doc_url = "https://muellerzr.github.io/fastinference"

git_url = "https://github.com/muellerzr/fastinference/tree/master/"

def custom_doc_links(name): return None
