# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Learner.get_preds": "00_inference.ipynb",
         "Learner.predict": "00_inference.ipynb",
         "TabularLearner.predict": "00_inference.ipynb",
         "base_error": "01_tabular_interpretation.ipynb",
         "PermutationImportance": "01_tabular_interpretation.ipynb"}

modules = ["inference.py",
           "tabular/interpretation.py"]

doc_url = "https://muellerzr.github.io/fastInference/"

git_url = "https://github.com/muellerzr/fastInference/tree/master/"

def custom_doc_links(name): return None
